fix: offset_encoding is required now
smjonas/inc-rename.nvim pull request #66
Opened 2024-11-23 22:23 UTC by rockyzhang24

Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".

2024-11-24 09:50 UTC, smjonas requested changes

2024-11-24 09:50 UTC, smjonas commented on lua/inc_rename/init.lua
> +    local ret = vim.api.util.make_position_params(win, client.offset_encoding)
```suggestion
    local ret = vim.lsp.util.make_position_params(win, client.offset_encoding)
```

2024-11-24 09:50 UTC, smjonas commented on lua/inc_rename/init.lua
> +    local ret = vim.api.util.make_position_params(win, client.offset_encoding)
Please rename variable to `params`

2024-11-24 09:50 UTC, smjonas commented on lua/inc_rename/init.lua
> +  local win = vim.api.nvim_get_current_win()
Please rename to `win_id`

2024-11-24 09:50 UTC, smjonas commented on lua/inc_rename/init.lua
> +      params = vim.tbl_extend('force', params, extra)
Style:
```suggestion
      params = vim.tbl_extend("force", params, extra)
```

2024-11-24 09:50 UTC, smjonas commented on lua/inc_rename/init.lua
> +      ret = vim.tbl_extend('force', ret, extra)
Style:
```suggestion
      ret = vim.tbl_extend("force", ret, extra)
```

2024-11-24 11:46 UTC, smjonas commented
Thank you very much for this PR! Currently, this is a breaking change for nightly users on a Nvim version before commit https://github.com/neovim/neovim/commit/2dcbfe78fcec5f73ce061bb24b718187b9c6b134 which I would like to avoid if possible.

We could wrap the call to `vim.lsp.buf_request` with `pcall` and fallback to the old variant if there was an error calling `buf_request` (i.e., `param` is a function instead of a dict).

2024-11-24 12:42 UTC, rockyzhang24 commented on lua/inc_rename/init.lua
> +    local ret = vim.api.util.make_position_params(win, client.offset_encoding)
Sure.

2024-11-24 12:42 UTC, rockyzhang24 commented on lua/inc_rename/init.lua
> +    local ret = vim.api.util.make_position_params(win, client.offset_encoding)
Oh, sorry, it's my bad.

2024-11-24 12:46 UTC, rockyzhang24 commented
Thank you so much for your review.

> this is a breaking change for nightly users on a Nvim version before commit

I already checked the Neovim version. Just pass a function as params to `buf_request` on version 0.11 or later.

2024-11-24 13:21 UTC, smjonas commented
> I think Nightly users will keep updating their Neovim to nightly version and won't stick to a specific commit.

That's a valid assumption. However, I have had issues with nightly users (of older nightly versions) reporting issues before so I think it is safer to add the retry mechanism. I can implement the workaround and will remove it once 0.11 has been released.

2024-11-25 21:50 UTC, smjonas commented
It got a bit complicated to implement the retry mechanism, so I will merge the PR without it. Thanks for your contribution!

2024-11-25 21:51 UTC, merged